#!/usr/bin/env python3
#
# This file is part of monitaringu-rei
#
# Copyright (C) 2021 Eric Le Bihan <eric.le.bihan.dev@free.fr>
#
# SPDX-License-Identifier: MIT
#

import os
import shutil
import subprocess
import sys

srcdir, builddir, output, mode, target = sys.argv[1:6]

args = ["cargo", "build", "--manifest-path", os.path.join(srcdir, "Cargo.toml")]
if mode == "release":
    args.append("--release")

outdir = os.path.join(builddir, "target")

if target != "native":
    outdir = os.path.join(outdir, target)
    args += ["--target", target]

exe = os.path.join(outdir, mode, os.path.basename(output))

subprocess.check_call(
    args,
    env=dict(
        os.environ,
        CARGO_HOME=os.path.join(srcdir, "target", "cargo-home"),
        CARGO_TARGET_DIR=os.path.join(builddir, "target"),
    ),
)

shutil.copy(exe, output)
